### ISSUE TITLE
XBox Controller Centering issue

### ISSUE THREAD

**Issue by evilC** [evilC/OneSwitch-Utilities#9]
When any of my apps grab control of the virtual joystick, it sets axes to 0, thus moving some axes to top/left

**Comment by evilC** [comment]
This seems to be because the apps call Shaul's ResetVJD() command, which moves the axes to 0.
Shaul says he can easily fix it.

**Comment by oneswitch** [comment]
Seems fixed with vJoy205-140415a.

Great news!
